### ISSUE TITLE
Promote Microcks Sponsors by Sharing BACKERS.md Across All Repos

### ISSUE THREAD

**Issue by yada** [microcks/.github#22]
### Reason/Context

To give proper recognition to our financial sponsors and backers, it's important to highlight their contributions throughout the Microcks project. Sharing our BACKERS.md file across all repositories not only promotes transparency but also encourages future sponsorship. It’s a nice way of saying thank you and spreading the word about the amazing support that drives our open-source community forward.

### Description

The idea is to include the BACKERS.md file, which lists all current financial sponsors and backers, in all of our Microcks-related repositories. This file will serve as a public acknowledgment and a thank-you note to those contributing to the project. It will also help raise awareness about how important this sponsorship is to maintaining and improving Microcks, encouraging others to join.

This initiative will:
- Ensure that every repository under the Microcks organization acknowledges the sponsors.
- Help promote the Open Collective page to attract more backers.
- Provide consistent visibility for our sponsors across all Microcks components.

### Implementation ideas

Recopy the BACKERS.md file from the main repository into every other repository under the Microcks organization.

| Needs/Constraints | Delivered components | Demonstrations | Documentation | Community resources |
| ----- | ----- | ----- | ----- |  ----- | 
| Backers | ✅ | ✅  | ✅ | ✅  |

**Comment by yada** [comment]
TODO:
- update table https://github.com/microcks/.github/issues/16#issuecomment-2298916186
- modify https://github.com/microcks/.github/blob/main/.github/workflows/global-replicator.yml
- Modify the backers' MD to add Bitso and sync automatically using our global-replicator.

**Comment by lbroudoux** [comment]
I think it would be better to align Backers with Adopters location. Those 2 files are going together: when you want to check who has adopted the techno, you may also want to check the sponsors/backers. So I would say that Backers should target **Delivered components** and **Community resources** only.

**Comment by yada** [comment]
Update table for #16 will be the sale as for Adopters:

| Needs/Constraints | Delivered components | Demonstrations | Documentation | Community resources |
| ----- | ----- | ----- | ----- |  ----- | 
| Backers | ✅ |  |  | ✅  |

**Comment by yada** [comment]
https://github.com/microcks/.github/issues/22#issuecomment-2370535433 updated

**Comment by yada** [comment]
Synced and merged ✅
