### ISSUE TITLE
Stale issues management workflow probably needs an update

### ISSUE THREAD

**Issue by lbroudoux** [microcks/.github#26]
### Reason/Context

Dependabot raises update requests on the `actions/stale` workflow synchronized from this repository. Update must be done there and then synchronized on other repos.

### Description

See for example: https://github.com/microcks/microcks-cli/pull/69

**Comment by lbroudoux** [comment]
@yada FYI

**Comment by yada** [comment]
WIP: testing here https://github.com/yada/test1/blob/main/.github/workflows/stale-issues-prs.yml

**Comment by yada** [comment]
Work fine using actions/stale v9 ✅
See: https://github.com/yada/test1/actions/runs/11403336423/job/31730193510

I am ready to update this action and sync this modification globally.
